name: Slaparoo
main: main.Main
version: 1.0
api-version: 1.13
commands:
  start:
    permission: slaparoo.start
    permission-message: "&cYou may not execute this command."
    description: Starts the game.
  gamespawn:
    permission: slaparoo.gamespawn
    permission-message: "&cYou may not execute this command."
    description: Set up to 5 game spawns.